"""Allow currency_code to be nullable

Revision ID: 6646323d2166
Revises: de185e34161e
Create Date: 2024-11-04 00:33:01.277844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6646323d2166'
down_revision = 'de185e34161e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
