"""Initial migration

Revision ID: de185e34161e
Revises: 
Create Date: 2024-11-04 00:31:28.762923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de185e34161e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cca', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('capital', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('subregion', sa.String(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('map_url', sa.String(), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('flag_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cca')
    )
    op.create_table('country_neighbours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('neighbour_country_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_neighbours')
    op.drop_table('countries')
    # ### end Alembic commands ###
