"""Allow currency to be nullable

Revision ID: f8e00d5b62b4
Revises: 6646323d2166
Create Date: 2024-11-04 00:33:44.799306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e00d5b62b4'
down_revision = '6646323d2166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
